# Generated by Django 4.0.4 on 2022-05-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheodoTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100000)),
                ('image', models.CharField(max_length=150)),
                ('fun_fact', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'theodo UK team',
            },
        ),
    ]
